name: Deploy to PyPI

on:
  release:
    types: [ published ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  BOOST_HASH:          3a336c8b1a917f7d9c55abba2905be99dade914bf9b829aab9d5fb6069b6ffcc
  BOOST_VERSION_MAJOR: 1
  BOOST_VERSION_MINOR: 76
  BOOST_VERSION_PATCH: 0

jobs:
  build_ubuntu_wheels:
    name:    Build wheels on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_macos_wheels:
    name:    Build wheels on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install boost
        run:  brew install boost
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_windows_wheels:
    name:    Build wheels on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache Boost
        id:   cache-boost
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/boost_${{ env.BOOST_VERSION_MAJOR }}_${{ env.BOOST_VERSION_MINOR }}_${{ env.BOOST_VERSION_PATCH }}
          key:  ${{ runner.OS }}-boost-${{ env.BOOST_VERSION_MAJOR }}_${{ env.BOOST_VERSION_MINOR }}_${{ env.BOOST_VERSION_PATCH }}
      - name:  Download boost
        if:    steps.cache-boost.outputs.cache-hit != 'true'
        shell: cmd
        run:   |
               C:\msys64\usr\bin\wget.exe https://boostorg.jfrog.io/artifactory/main/release/${{ env.BOOST_VERSION_MAJOR }}.${{ env.BOOST_VERSION_MINOR }}.${{ env.BOOST_VERSION_PATCH }}/source/boost_${{ env.BOOST_VERSION_MAJOR }}_${{ env.BOOST_VERSION_MINOR }}_${{ env.BOOST_VERSION_PATCH }}.7z --no-check-certificate
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Building boost
        if:   steps.cache-boost.outputs.cache-hit != 'true'
        run:  |
              "/c/Program Files/7-Zip/7z.exe" x boost_${{ env.BOOST_VERSION_MAJOR }}_${{ env.BOOST_VERSION_MINOR }}_${{ env.BOOST_VERSION_PATCH }}.7z "-o${{github.workspace}}"
              cd boost_${{ env.BOOST_VERSION_MAJOR }}_${{ env.BOOST_VERSION_MINOR }}_${{ env.BOOST_VERSION_PATCH }}
              ./bootstrap.bat
              ./b2.exe -j8 address-model=64 link=static threading=multi runtime-link=shared variant=release --build-type=minimal
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
      #        env:
      #          CIBW_ENVIRONMENT_WINDOWS: "Boost_USE_STATIC_LIBS='ON' Boost_USE_MULTITHREADED='ON' Boost_USE_STATIC_RUNTIME='OFF' BOOST_ROOT='${{github.workspace}}\boost_${{ env.BOOST_VERSION_MAJOR }}_${{ env.BOOST_VERSION_MINOR }}_${{ env.BOOST_VERSION_PATCH }}' BOOST_INCLUDEDIR='${{github.workspace}}\boost_${{ env.BOOST_VERSION_MAJOR }}_${{ env.BOOST_VERSION_MINOR }}_${{ env.BOOST_VERSION_PATCH }}\include' BOOST_LIBRARYDIR='${{github.workspace}}\boost_${{ env.BOOST_VERSION_MAJOR }}_${{ env.BOOST_VERSION_MINOR }}_${{ env.BOOST_VERSION_PATCH }}\lib'"
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_m1_wheels:
    name:    Build wheels for Apple Silicon
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install Z3
        run:  |
              curl -L -H "Authorization: Bearer QQ==" -o boost-${{ env.BOOST_VERSION_MAJOR }}.${{ env.BOOST_VERSION_MINOR }}.${{ env.BOOST_VERSION_PATCH }}.big_sur.bottle.tar.gz https://ghcr.io/v2/homebrew/core/z3/blobs/sha256:${{ env.BOOST_HASH }}
              brew install -f boost-${{ env.BOOST_VERSION_MAJOR }}.${{ env.BOOST_VERSION_MINOR }}.${{ env.BOOST_VERSION_PATCH }}.big_sur.bottle.tar.gz
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.1
        env:
          CIBW_ARCHS_MACOS: arm64
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name:    Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'
      - name: Install boost
        run:  sudo apt install libboost-all-dev
      - name: Install dependencies
        run:  pip install -q build
      - name: Build sdist
        run:  python -m build --sdist
      - name: Test sdist
        run:  pip install --verbose dist/*.tar.gz
        env:
          CC:  "gcc-10"
          CXX: "g++-10"
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  upload_pypi:
    needs: [ build_wheels, build_sdist, build_m1_wheels ]
    runs-on: ubuntu-latest
    if:      github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@master
        with:
          user:          __token__
          password:      ${{ secrets.pypi_password }}
          skip_existing: true
          verbose:       true
